set -g prefix 'C-Space' # Rebind prefix
set -g mouse on # enable mouse support
set -g base-index 1 # Start numbering at 1
set -g renumber-windows on # autorenumber windows
setw -g pane-base-index 1 # Start pane numbering at 1
setw -g automatic-rename on # autorename windows
setw -g mode-keys vi # Use vim keybinds in copy mode

# Pane
set -g pane-border-style 'fg=black bg=black'
set -g pane-active-border-style 'bg=black fg=#29AB87'

# Status bar
set -g status-interval 1
set -g status-bg black
set -g status-fg '#29AB87'
set -g status-right '[%H:%M:%S] '

# Key Bindings
bind r source-file ~/.config/tmux/tmux.conf \; display "Config Reloaded!"   # Easy config reload
bind a send-prefix      # send commands to nested sessions

# Pane movement
bind -n C-h select-pane -L   # move left
bind -n C-j select-pane -D   # move down
bind -n C-k select-pane -U   # move up
bind -n C-l select-pane -R   # move right
bind -n C-> swap-pane -D     # swap current pane with next
bind -n C-< swap-pane -U     # swap current pane with prev

# Window split
bind v split-window -v  # split window vertical
bind h split-window -h  # split window horizontal

# Bootstrap TPM
set-environment -g TMUX_PLUGIN_MANAGER_PATH '~/.local/share/tmux/plugins/'
if "test ! -d ~/.local/share/tmux/plugins/tpm" \
   "run 'git clone https://github.com/tmux-plugins/tpm ~/.local/share/tmux/plugins/tpm && ~/.local/share/tmux/plugins/tpm/bin/install_plugins'"

# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

# Continuum Config
set -g @continuum-save-interval '5'

# Set options if using kitty terminal
if-shell '[[ "$TERM" == "xterm-kitty" ]]' {
  set-option -g default-shell /bin/zsh
  set -g @tpm_plugins 'catppuccin/tmux' # Enable catppuccin theme
  source-file ~/.config/tmux/theme.conf # Source catppuccin config
}

# Initialize TPM
# Keep at bottom of tmux.conf
run '~/.local/share/tmux/plugins/tpm/tpm'
