
# █▀▄▀█ █▀█ █▄░█ █ ▀█▀ █▀█ █▀█ █▀
# █░▀░█ █▄█ █░▀█ █ ░█░ █▄█ █▀▄ ▄█


# Set your monitor configuration here
# See https://wiki.hyprland.org/Configuring/Monitors/

#monitor = ,1366x768,auto,1
#monitor = ,1920x1080,auto,1
#monitor = ,1920x1080@120,auto,1
#monitor = ,1920x1200,auto,1
#monitor = ,1920x1200@120,auto,1
#monitor = ,2560x1440,auto,1
#monitor = ,2560x1440@120,auto,1
#monitor = ,3440x1440,auto,1
#monitor = ,3440x1440@120,auto,1
